### PR TITLE
Respaces homepage, buttons, header/logo/subheader/footer

### PR DESCRIPTION
**Pull request by CelestialSloth**
This pull request respaces and reformats the homepage, buttons, header, logo, subheader, and footer according to the Figma file.

Notes:
* This is based on the homepage version that the designer made, plus the testimonials section. Therefore, it does include the vendor application button and does not include upcoming events. Let me know if I should add/remove those sections.
* I did not edit the navbar or strawberry component spacing, so the spacing around those components will appear large. (I think Cameron is working on that.)
* For screen sizes below 768px, the two images (the poster and the peach) are set to be the width of the screen (minus the 16px margins). Let me know if I should put a different maximum width on them.
* I set the maximum width of the page content to be 1035px, based on the width of the "About" homepage section in the Figma file.
* The "About" section switches to desktop at 1024px instead of 768px--this was a judgement I made since I thought it looked awkward otherwise; I can switch it back to 768px and reduce the image width if we want.
localhost_3000_ (1)
localhost_3000_(iPhone SE)

### CODE REVIEW

**Comment by michellewong793** [comment]
image

can you add spacing between the testimonials? like 36px? 
also, can you try the body font that is used in the descriptions? (small and doesnt need to be italic)

**Comment by CelestialSloth** [comment]
I added the 36px of spacing between testimonials and switched the font to Helvetica regular.  (By default it is 24px font size, 16px on mobile.) Let me know if there was a different description font you were thinking of

**Comment by michellewong793** [comment]
one more thing: i would add the same amount of spacing between the footer - the top should be the same as the bottom of the text. 
otherwise looks good, will send to designer 
image

**Comment by michellewong793** [comment]
image
can you make the footer spacing the same as top and bottom of the text for mobile as well? also the font size should be slightly smaller, maybe 24px?

**Comment by CelestialSloth** [comment]
I fixed the spacing issue in the footer, made the mobile font size be 24px for the "Get updates..." text, and added an Upcoming Events section based off the figma file. I implemented what the designer did and translated it to mobile, however it differs from your mobile design which includes a poster. Let me know if I should change that/how the poster should be included and if it should be included on desktop as well.
Screenshot 2023-06-19 at 2 09 30 PM
Screenshot 2023-06-19 at 2 09 42 PM

**Comment by michellewong793** [comment]
can you actually remove the names of folks from the testimonials? i think it's better to be anonymous !

**Comment by CelestialSloth** [comment]
Screenshot 2023-06-22 at 10 44 04 AM

**Comment by CelestialSloth** [comment]
Screenshot 2023-06-22 at 10 48 16 AM

**Pull request merged**
