### PR TITLE
Implements how to order email, item deletion, and design for shop/item pages

### PR DESCRIPTION
**Pull request by CelestialSloth**
This pr implements designs for the following:
- new shop form, 
- new item form, 
- shop edit form, 
- item edit form, 
- shop display page, 
- item display page, 
- and account page. 
Screenshot 2023-08-01 at 4 57 02 PM
Screenshot 2023-08-02 at 12 38 33 PM
Screenshot 2023-08-02 at 12 39 21 PM
Screenshot 2023-08-02 at 12 39 38 PM
Screenshot 2023-08-02 at 12 41 02 PM
Screenshot 2023-08-02 at 12 42 46 PM
Screenshot 2023-08-02 at 12 43 56 PM

It also creates the following reusable components:
- Input
- Label
- BannerNotification (needs more work to be properly implemented)
- Clickable (a component that makes its children mimic the styling of a button)
- Card (a card with an image and text)
- ItemCard (a card tailored to displaying an item)
- NewCard (a clickable with a plus sign, indicating it can be used to add something like an image, shop, or item)
- Deletable image (displays an image with a trash icon in the corner, which can be clicked on to "delete" the image)

### CODE REVIEW

**Comment by CelestialSloth** [comment]
This pr now also includes a functional order button. When clicked, a modal opens with instructions for ordering.
Screenshot 2023-08-02 at 6 03 08 PM

**Comment by CelestialSloth** [comment]
This pr now allows items to be deleted via the shop edit page.
Screenshot 2023-08-03 at 2 11 36 PM Screenshot 2023-08-03 at 2 11 45 PM

**Comment by michellewong793** [comment]
lets merge this before it gets too big!

**Comment by michellewong793** [comment]
make sure all capitalization is consistent, and the modules exported have brackets around them so the deployment works!

**Comment by michellewong793** [comment]
image
still with these errors

**Review by michellewong793 — APPROVED** [review]
approved with changes

**Pull request merged**
